-- Role: esubale
-- DROP ROLE IF EXISTS esubale;

CREATE ROLE esubale WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:zh1Ptm/mC8OSgYFGDx/Nig==$w4lWEQG4Nw5r/HjI060KdxfspfRMMkiQfXyYNtffczg=:ZYFrJyruvyzpi08slTXD6nfZbGszWvuzqu8oOVkzCA8=';


  CREATE DATABASE "EsuTmsDb"
  OWNER esubale;